<?xml version="1.0" encoding="utf-8"?>
<appList>
  <collection>
    <!--<serviceApp name="TestApp1" description="Shows how SACS works." environment="Development" path="C:\Development\Projects\Open Box\SACS\Tests\SACS.TestApp\bin\Debug" entryFile="SACS.TestApp.exe" assembly="SACS.TestApp" startupType="Automatic" configFilePath="C:\Development\Projects\Open Box\SACS\Tests\SACS.TestApp\bin\Debug\SACS.TestApp.exe.config" schedule="*/5 * * * *"></serviceApp>
    <serviceApp name="TestApp2" description="2 for 1: Same app and demonstrated exception handling." environment="Development" path="C:\Development\Projects\Open Box\SACS\Tests\SACS.TestApp\bin\Debug" entryFile="SACS.TestApp.exe" assembly="SACS.TestApp" startupType="1" configFilePath="C:\Development\Projects\Open Box\SACS\Tests\SACS.TestApp\bin\Debug\AppExtra2.config" schedule="0,3,6,9,12,15,18,21,24,27,30,33,36,39,42,45,48,51,54,57 * * * *"></serviceApp>-->
    <serviceApp name="TestApp1_Home" description="Shows how SACS works. (Home)" environment="Home" path="E:\Development\SACS\Head\Tests\SACS.TestApp\bin\Debug" entryFile="SACS.TestApp.exe" assembly="SACS.TestApp" startupType="Automatic" configFilePath="E:\Development\SACS\Head\Tests\SACS.TestApp\bin\Debug\SACS.TestApp.exe.config" schedule="* * * * *"></serviceApp>
    <!--<serviceApp name="TestApp2_Home" description="2 for 1: Same app and demonstrated exception handling. (Home)" environment="Home" path="E:\Development\SACS\Head\Tests\SACS.TestApp\bin\Debug" entryFile="SACS.TestApp.exe" assembly="SACS.TestApp" startupType="1" configFilePath="E:\Development\SACS\Head\Tests\SACS.TestApp\bin\Debug\AppExtra2.config" schedule="0,3,6,9,12,15,18,21,24,27,30,33,36,39,42,45,48,51,54,57 * * * *" username="MachineTest" password="gPNkPi/pw6E/KrzTpk38+w=="></serviceApp>-->
  </collection>
</appList>